"""sync_history_changes

Revision ID: 1567fb6768ce
Revises: d6e7f8a9b0c1
Create Date: 2026-07-14 17:09:05.628145

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1567fb6768ce'
down_revision: Union[str, None] = '63fb973c986c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_log_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('moysklad_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('has_image_field', sa.Boolean(), nullable=False),
    sa.Column('images_in_xml', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sync_log_id'], ['sync_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_changes_moysklad_id'), 'sync_changes', ['moysklad_id'], unique=False)
    op.create_index(op.f('ix_sync_changes_sync_log_id'), 'sync_changes', ['sync_log_id'], unique=False)
    op.add_column('sync_logs', sa.Column('changes_only', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('sync_logs', sa.Column('products_in_xml', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sync_logs', sa.Column('xml_file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_logs', 'xml_file')
    op.drop_column('sync_logs', 'products_in_xml')
    op.drop_column('sync_logs', 'changes_only')
    op.drop_index(op.f('ix_sync_changes_sync_log_id'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_moysklad_id'), table_name='sync_changes')
    op.drop_table('sync_changes')
    # ### end Alembic commands ###
