"""add_is_hot_flag

Revision ID: 63fb973c986c
Revises: 8809a333fe51
Create Date: 2026-07-10 16:18:09.379442

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '63fb973c986c'
down_revision: Union[str, None] = '8809a333fe51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_hot', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_products_is_hot'), 'products', ['is_hot'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_is_hot'), table_name='products')
    op.drop_column('products', 'is_hot')
    # ### end Alembic commands ###
