"""add_is_new_is_sale_flags

Revision ID: 8809a333fe51
Revises: c1d2e3f4a5b6
Create Date: 2026-07-08 19:48:08.186063

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8809a333fe51'
down_revision: Union[str, None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_new', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('is_sale', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_products_is_new'), 'products', ['is_new'], unique=False)
    op.create_index(op.f('ix_products_is_sale'), 'products', ['is_sale'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_is_sale'), table_name='products')
    op.drop_index(op.f('ix_products_is_new'), table_name='products')
    op.drop_column('products', 'is_sale')
    op.drop_column('products', 'is_new')
    # ### end Alembic commands ###
