"""add_user_activation_and_ext_code

Revision ID: 8f1ff656fab5
Revises: f8a9b0c1d2e3
Create Date: 2026-07-02 14:33:29.555320

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8f1ff656fab5'
down_revision: Union[str, None] = 'f8a9b0c1d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('moysklad_ext_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'moysklad_ext_code')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
